namespace Center.Server
{
    using System;

    public enum ePackageType
    {
        ALLOW_USER_LOGIN = 3,
        B_BUGLE = 0x48,
        BATTLE_GOUND_OPEN_CLOSE = 0x58,
        CONSORTIA_ALLY_ADD = 0x93,
        CONSORTIA_BOSS_AWARD = 0xb9,
        CONSORTIA_BOSS_CLOSE = 0xbb,
        CONSORTIA_BOSS_CREATE = 0xb7,
        CONSORTIA_BOSS_DIE = 0xbc,
        CONSORTIA_BOSS_EXTEND_AVAILABLE = 0xb6,
        CONSORTIA_BOSS_INFO = 180,
        CONSORTIA_BOSS_RELOAD = 0xb8,
        CONSORTIA_BOSS_UPDATE_BLOOD = 0xba,
        CONSORTIA_BOSS_UPDATE_RANK = 0xb5,
        CONSORTIA_CREATE = 130,
        CONSORTIA_CHAT = 0x9b,
        CONSORTIA_DELETE = 0x83,
        CONSORTIA_FIGHT = 0x9e,
        CONSORTIA_OFFER = 0x9c,
        CONSORTIA_RESPONSE = 0x80,
        CONSORTIA_RICHES = 0x9d,
        CONSORTIA_UPGRADE = 0x9f,
        CHARGE_MONEY = 9,
        CHAT_PERSONAL = 0x25,
        DISPATCHES = 0x7b,
        EVENT_RANKING = 90,
        FIGHTFOOT_BALL_TIME = 0x59,
        FRIEND_RESPONSE = 0xa6,
        FRIEND_STATE = 0xa5,
        GET_LIGHTRIDDLE_INFO = 2,
        IM_CMD = 160,
        IP_PORT = 240,
        KIT_OFF_PLAYER = 0xf2,
        KITOFF_USER = 2,
        LEAGUE_OPEN_CLOSE = 0x57,
        LIGHTRIDDLE_INFO = 1,
        LOGIN = 1,
        LUCKSTAR_REWARD_RECORD = 4,
        MACRO_DROP = 0xb2,
        MAIL_RESPONSE = 0x75,
        MARRY_ROOM_DISPOSE = 0xf1,
        MARRY_ROOM_INFO_TO_PLAYER = 14,
        MESSAGE = 0x76,
        PING = 12,
        RANKING_LIGHTRIDDLE = 1,
        Rate = 0xb1,
        RSAKey = 0,
        SCENE_CHAT = 0x13,
        SEND_LIGHTRIDDLE_AWARD = 3,
        SHUTDOWN = 15,
        SYS_CMD = 11,
        SYS_MESS = 0x26,
        SYS_NOTICE = 10,
        UPDATE_ASS = 7,
        UPDATE_CONFIG_STATE = 8,
        UPDATE_PLAYER_MARRIED_STATE = 13,
        UPDATE_RANKING_LIGHTRIDDLE = 2,
        USER_OFFLINE = 4,
        USER_ONLINE = 5,
        USER_STATE = 6,
        WORLD_BOSS_FIGHTOVER = 0x52,
        WORLD_BOSS_RANK = 0x51,
        WORLD_BOSS_ROOMCLOSE = 0x53,
        WORLD_BOSS_START = 80,
        WORLD_BOSS_UPDATE_BLOOD = 0x4f,
        WORLD_BOSS_UPDATEBLOOD = 0x54,
        WORLD_BOSS_VIEW_RANK = 0x56,
        WORLD_EVENT = 0x5b,
        WORLDBOSS_PRIVATE_INFO = 0x55
    }
}

