namespace Game.Logic.Protocol
{
    using System;

    public enum eFightPackageType
    {
        CHANGE_GAME_TYPE = 0x48,
        CHAT = 0x13,
        DISCONNECT = 0x53,
        DISCONNECT_PLAYER = 0x22,
        FIGHT_NPC = 0x58,
        FIND_CONSORTIA_ALLY = 0x4d,
        FOOTBALL_TAKE_OUT = 0x57,
        KIT_OFF_PLAYER = 4,
        LOG_FIGHT = 5,
        LOGIN = 1,
        PLAYER_ADD_ACTIVE_MONEY = 0x59,
        PLAYER_ADD_GOLD = 0x26,
        PLAYER_ADD_GOXU = 100,
        PLAYER_ADD_GP = 0x27,
        PLAYER_ADD_GIFTTOKEN = 0x4b,
        PLAYER_ADD_HEALSTONE = 0x49,
        PLAYER_ADD_ITEM = 0x25,
        PLAYER_ADD_LEAGUEMONEY = 0x54,
        PLAYER_ADD_MEDAL = 0x4c,
        PLAYER_ADD_MONEY = 0x4a,
        PLAYER_ADD_OFFER = 0x33,
        PLAYER_ADD_PRESTIGE = 0x55,
        PLAYER_ADD_ROBRICHES = 0x34,
        PLAYER_ADD_TEMPLATE = 0x2e,
        PLAYER_ADD_TEMPLATE1 = 0x30,
        PLAYER_CLEAR_BAG = 0x35,
        PLAYER_CONSORTIAFIGHT = 0x2a,
        PLAYER_ON_GAME_OVER = 0x23,
        PLAYER_ONKILLING_LIVING = 40,
        PLAYER_ONMISSION_OVER = 0x29,
        PLAYER_REMOVE_GOLD = 0x2c,
        PLAYER_REMOVE_GP = 0x31,
        PLAYER_REMOVE_MONEY = 0x2d,
        PLAYER_REMOVE_OFFER = 50,
        PLAYER_SEND_CONSORTIAFIGHT = 0x2b,
        PLAYER_UPDATE_REST_COUNT = 0x56,
        PLAYER_USE_PROP_INGAME = 0x24,
        REMOVE_PLAYER = 70,
        ROOM_CREATE = 0x40,
        ROOM_REMOVE = 0x41,
        ROOM_START_GAME = 0x42,
        ROOM_STOP_GAME = 0x44,
        RSAKey = 0,
        SEND_GAME_PLAYER_ID = 0x21,
        SEND_TO_GAME = 2,
        SEND_TO_GAME_ALL_PLAYER = 0x47,
        SEND_TO_ROOM = 0x43,
        SEND_TO_USER = 0x20,
        SYS_NOTICE = 3,
        UPDATE_ROOM_ID = 0x45,
        UpdateRoom = 0x45
    }
}

