namespace Bussiness
{
    using System;

    public enum BuffType
    {
        ActivityDungeonBubble = 0x72,
        ActivityDungeonNet = 0x73,
        AddBloodGunCount = 0x1a,
        AddCritical = 14,
        AddDamage = 12,
        AddDander = 0x10,
        AddMaxBlood = 0x12,
        AddPercentDamage = 20,
        AddPercentDefance = 0x18,
        AddProperty = 0x11,
        ArmorPiercer = 0x2724,
        Atom = 0x2726,
        CARD_BUFF = 4,
        CONSORTIA = 3,
        ConsortionAddBloodGunCount = 0x65,
        ConsortionAddCritical = 0x67,
        ConsortionAddDamage = 0x66,
        ConsortionAddEffectTurn = 0x6c,
        ConsortionAddEnergy = 0x6b,
        ConsortionAddMaxBlood = 0x68,
        ConsortionAddOfferRate = 0x6d,
        ConsortionAddPercentGoldOrGP = 110,
        ConsortionAddProperty = 0x69,
        ConsortionAddSpellCount = 0x6f,
        ConsortionReduceDander = 0x70,
        ConsortionReduceEnergyUse = 0x6a,
        CustomAddGuard = 11,
        DamageEffect = 0x1d,
        Defend = 6,
        DisenableFly = 8,
        DoNotMove = 0x17,
        ExemptEnergy = 15,
        Fatal = 0x2721,
        Firing = 2,
        GreenFiring = 0x1c,
        GuardEffect = 30,
        IceFronze = 0x271f,
        INDIAN = 0x22,
        LimitMaxForce = 9,
        Local = 1,
        LockAngel = 3,
        LockState = 0x3e8,
        NIUTOU = 0x21,
        NoHole = 5,
        NoHoleEffect = 0x2721,
        Pay = 2,
        PET_BUFF = 5,
        ReduceContinueDamage = 0x16,
        ReduceDamage = 0x13,
        ReducePoisoning = 0x19,
        ResistAttack = 0x1b,
        ResolveHurt = 10,
        SACRED_BLESSING = 0x1f,
        SACRED_SHIELD = 0x20,
        Save_Life = 0x33,
        SetDefaultDander = 0x15,
        Targeting = 7,
        Tired = 1,
        Turn = 0,
        TurnAddDander = 13,
        Weakness = 4,
        WorldBossAddDamage = 0x196,
        WorldBossAncientBlessings = 0x195,
        WorldBossAttrack = 0x191,
        WorldBossAttrack_MoneyBuff = 0x193,
        WorldBossHP = 400,
        WorldBossHP_MoneyBuff = 0x192,
        WorldBossMetalSlug = 0x194
    }
}

